# Generated by Django 4.2.7 on 2024-01-29 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='relic_list',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.IntegerField(unique=True)),
                ('ccma_name', models.TextField(null=True)),
                ('ccba_mnm1', models.TextField(null=True)),
                ('ccba_mnm2', models.TextField(null=True)),
                ('ccba_kdcd', models.TextField(null=True)),
                ('ccba_ctcd', models.TextField(null=True)),
                ('ccba_asno', models.TextField(null=True)),
            ],
            options={
                'db_table': 'relic_list',
            },
        ),
        migrations.CreateModel(
            name='relic_detail',
            fields=[
                ('relic_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ccba_mnm1', models.TextField(null=True)),
                ('ccba_mnm2', models.TextField(null=True)),
                ('ccba_kdcd', models.TextField(null=True)),
                ('ccba_asno', models.TextField(null=True)),
                ('ccba_ctcd', models.TextField(null=True)),
                ('ccba_cpno', models.TextField(null=True)),
                ('longitude', models.TextField(null=True)),
                ('latitude', models.TextField(null=True)),
                ('ccma_name', models.TextField(null=True)),
                ('gcode_name', models.TextField(null=True)),
                ('bcode_name', models.TextField(null=True)),
                ('mcode_name', models.TextField(null=True)),
                ('scode_name', models.TextField(null=True)),
                ('ccba_quan', models.TextField(null=True)),
                ('ccba_asdt', models.TextField(null=True)),
                ('ccba_lcad', models.TextField(null=True)),
                ('ccce_name', models.TextField(null=True)),
                ('ccba_poss', models.TextField(null=True)),
                ('ccba_admin', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('list_id', models.ForeignKey(db_column='list_id', on_delete=django.db.models.deletion.CASCADE, to='relic.relic_list')),
            ],
            options={
                'db_table': 'relic_detail',
            },
        ),
    ]
