# Generated by Django 4.2.7 on 2024-01-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='relic_list',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('ccma_name', models.TextField()),
                ('ccba_mnm1', models.TextField()),
                ('ccba_mnm2', models.TextField()),
                ('ccba_kdcd', models.TextField()),
                ('ccba_ctcd', models.TextField()),
                ('ccba_asno', models.TextField()),
            ],
        ),
    ]
